name: Wails Build

on: [ push, pull_request, release]

jobs:

  build_mac:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 16.14.2

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Wails CLI Build
      run: wails build -clean -f

    - name: Create Build Folder & DMG
      run: |
        mv build/bin build/tify-desktop
        hdiutil create -srcfolder build/tify-desktop tify-desktop-${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}.dmg

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tify-desktop-${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}
        path: tify-desktop-${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}.dmg


  build_linux:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: install dependencies
      run: sudo apt-get install -yqq libwebkit2gtk-4.0-dev libgtk-3-dev build-essential pkg-config

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 16.14.2

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Wails CLI Build
      run: wails build -clean -f

    - name: Create Build Folder
      run: |
        mkdir build/tify-desktop
        mv build/bin/tify-desktop build/tify-desktop/${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tify-desktop-${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}
        path: tify-desktop-${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}
