name: Wails Build

on: [ push ]

jobs:

  upload-release:
      runs-on: ubuntu-22.04
      needs: [build_mac, build_linux, build_windows]

      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: download artifacts
        uses: actions/download-artifact@v1
        with:
          name: uploads
      - name: upload macos
        id: upload-macos
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: tify-desktop-${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}.dmg
          asset_name: tify-desktop-${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}.dmg
      - name: upload linux
        id: upload-linux
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/tify-desktop/${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}
          asset_name: ${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}
      - name: upload windows
        id: upload-windows
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/tify-desktop/${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}.exe
          asset_name: ${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}.exe

  build_mac:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Wails CLI Build
      run: wails build -clean -f

    - name: Create Build Folder & DMG
      run: |
        mv build/bin build/tify-desktop
        hdiutil create -srcfolder build/tify-desktop tify-desktop-${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}.dmg

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: uploads
        path: tify-desktop-${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}.dmg

  build_linux:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v2

    - name: install dependencies
      run: sudo apt-get install -yqq libwebkit2gtk-4.0-dev libgtk-3-dev build-essential pkg-config

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Wails CLI Build
      run: wails build -clean -f

    - name: Create Build Folder
      run: |
        mkdir build/tify-desktop
        mv build/bin/tify-desktop build/tify-desktop/${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: build/tify-desktop/${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}

  build_windows:
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Wails CLI Build
      run: wails build -clean -f

    - name: Create Build Folder
      run: |
        mkdir build/tify-desktop
        mv build/bin/tify-desktop.exe build/tify-desktop/${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}.exe

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: build/tify-desktop/${{ github.ref_name}}-${{ runner.os }}-${{ runner.arch }}.exe
